// Real Trace tokens (opensea.io/collection/traceart): tokenId, role, traits, image extension.
// Characters are decoded tokens; bases are Method Base; encoders are Binary, Base64, or Punched card.
export const CATALOG_DATA: [number, "character" | "base" | "encoder", [string, string][], string][] = [
  [2, "character", [["Body","Striped Tee"],["Features","Chinstrap"],["Headwear","Pompadour"]], "svg"],
  [4, "character", [["Body","Frayed Vest"],["Eyewear","Eyepatch"],["Headwear","Crossed Brim"]], "svg"],
  [5, "character", [["Back","Golf Driver"],["Body","Blazer and Chain"],["Features","Goatee"],["Headwear","Textured Crop"]], "svg"],
  [7, "character", [["Body","Hoodie"],["Eyewear","Square Shades"],["Features","Chinstrap"],["Headwear","Headset"]], "svg"],
  [9, "character", [["Body","Striped Tee"],["Headwear","Textured Crop"]], "svg"],
  [12, "character", [["Body","Striped Tee"],["Eyewear","Visor"],["Features","Pipe"],["Headwear","Crossed Brim"]], "svg"],
  [13, "character", [["Body","Track Hoodie"],["Features","Braided Beard"]], "svg"],
  [14, "character", [["Body","Striped Tee"],["Eyewear","Shutter Shades"],["Features","Cigarette"],["Headwear","Combat Helmet"]], "svg"],
  [15, "character", [["Body","Turtleneck"],["Features","Cigarette"],["Headwear","Visor Helmet"]], "svg"],
  [19, "character", [["Back","Bat"],["Body","Hoodie"],["Eyewear","Cat-Eye Shades"],["Features","Grin"],["Headwear","Textured Crop"]], "svg"],
  [21, "character", [["Back","Crossed Blades"],["Body","Frayed Vest"],["Headwear","Textured Crop"],["Mask","Flame Mask"]], "svg"],
  [25, "character", [["Back","Staff"],["Body","High Collar"],["Eyewear","Round Shades"],["Features","Closed Eyes"],["Headwear","Bald"]], "svg"],
  [27, "character", [["Back","Skis"],["Body","Business Suit"],["Features","Scowl"],["Headwear","Curly Bob"]], "svg"],
  [28, "character", [["Body","Business Suit"],["Eyewear","Eyepatch"],["Features","Cigarette"],["Headwear","Crossed Brim"]], "svg"],
  [29, "character", [["Body","Business Suit"],["Eyewear","Square Shades"],["Features","Blank Stare"],["Headwear","Combat Helmet"]], "svg"],
  [30, "character", [["Body","Hoodie"],["Headwear","Durag"],["Mask","Flame Mask"]], "svg"],
  [31, "character", [["Body","Tank and Chain"],["Eyewear","Round Shades"],["Features","Grin"],["Headwear","Curly Bob"]], "svg"],
  [33, "character", [["Body","Striped Tee"],["Eyewear","Square Shades"],["Features","Handlebar"],["Headwear","Curly Bob"]], "svg"],
  [1, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [3, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [6, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [8, "base", [["Form","Inverted"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [10, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [11, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [16, "base", [["Form","Inverted"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [17, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Grey"]], "png"],
  [18, "base", [["Form","Blink"],["Method","Base"],["Motion","Animated"],["Palette","Dark"]], "png"],
  [20, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [22, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [23, "base", [["Form","Inverted"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [24, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [26, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [32, "base", [["Form","Classic"],["Method","Base"],["Motion","Static"],["Palette","Dark"]], "png"],
  [34, "base", [["Form","Inverted"],["Method","Base"],["Motion","Static"],["Palette","Light"]], "png"],
  [611, "encoder", [["Form","Classic"],["Method","Punched card"],["Motion","Animated"],["Palette","Dark"]], "png"],
  [789, "encoder", [["Form","Wave"],["Method","Punched card"],["Motion","Animated"],["Palette","Grey"]], "png"],
  [123, "encoder", [["Form","Classic"],["Method","Binary"],["Motion","Static"],["Palette","Dark"]], "png"],
  [125, "encoder", [["Form","Classic"],["Method","Binary"],["Motion","Static"],["Palette","Dark"]], "png"],
  [844, "encoder", [["Form","Classic"],["Method","Punched card"],["Motion","Animated"],["Palette","Light"]], "png"],
  [139, "encoder", [["Form","Classic"],["Method","Binary"],["Motion","Static"],["Palette","Light"]], "png"],
  [143, "encoder", [["Form","Classic"],["Method","Binary"],["Motion","Static"],["Palette","Dark"]], "png"],
  [145, "encoder", [["Form","Classic"],["Method","Binary"],["Motion","Static"],["Palette","Grey"]], "png"],
  [148, "encoder", [["Form","Glitch"],["Method","Binary"],["Motion","Animated"],["Palette","Light"]], "png"],
  [149, "encoder", [["Form","Scatter"],["Method","Base64"],["Motion","Animated"],["Palette","Grey"]], "png"],
  [150, "encoder", [["Form","Classic"],["Method","Base64"],["Motion","Static"],["Palette","Grey"]], "png"],
  [163, "encoder", [["Form","Classic"],["Method","Base64"],["Motion","Static"],["Palette","Dark"]], "png"],
  [166, "encoder", [["Form","Classic"],["Method","Base64"],["Motion","Static"],["Palette","Dark"]], "png"],
  [168, "encoder", [["Form","Scatter"],["Method","Base64"],["Motion","Animated"],["Palette","Light"]], "png"],
];
