// Rebuilds the real 35×21 glyph grid of every decoded Trace character from its SVG art.
// Each SVG places one of five glyph shapes per cell; ink coverage maps them to the shade ramp.
import { readFileSync, writeFileSync } from "node:fs";

const CELL_W = 1233;
const CELL_H = 2048;
const TOP = 1556;
const COLS = 35;
const ROWS = 21;

function inkArea(d) {
  let total = 0;
  for (const sub of d.split(/(?=M)/)) {
    const pts = [...sub.matchAll(/(-?\d+(?:\.\d+)?)[ ,](-?\d+(?:\.\d+)?)/g)].map((m) => [Number(m[1]), Number(m[2])]);
    let area = 0;
    for (let i = 0; i < pts.length; i++) {
      const [x1, y1] = pts[i];
      const [x2, y2] = pts[(i + 1) % pts.length];
      area += x1 * y2 - x2 * y1;
    }
    total += Math.abs(area) / 2;
  }
  return total;
}

const source = readFileSync("src/lib/trace/catalog-data.ts", "utf8");
const ids = [...source.matchAll(/\[(\d+), "character"/g)].map((m) => Number(m[1]));
const grids = {};
for (const id of ids) {
  const svg = readFileSync(`public/trace/${id}.svg`, "utf8");
  const glyphOf = new Map();
  for (const m of svg.matchAll(/<path id="(g\d+)" d="([^"]*)"/g)) {
    const coverage = inkArea(m[2]) / (CELL_W * CELL_H);
    // The full block is one rectangle; the dark shade has the same outline cut into a pattern.
    const solid = m[2].split("M").length === 2;
    glyphOf.set(m[1], coverage < 0.06 ? "." : coverage < 0.16 ? "░" : coverage < 0.5 ? "▒" : solid ? "█" : "▓");
  }
  const cells = Array.from({ length: ROWS }, () => Array(COLS).fill(" "));
  for (const m of svg.matchAll(/<use href="#(g\d+)" x="(\d+)" y="(\d+)"/g)) {
    const col = Math.round(Number(m[2]) / CELL_W);
    const row = Math.round((Number(m[3]) - TOP) / CELL_H);
    if (row >= 0 && row < ROWS && col >= 0 && col < COLS) cells[row][col] = glyphOf.get(m[1]) ?? "?";
  }
  grids[id] = cells.map((row) => row.join(""));
}

const body = Object.entries(grids)
  .map(([id, rows]) => `  ${id}: [\n${rows.map((row) => `    ${JSON.stringify(row)},`).join("\n")}\n  ],`)
  .join("\n");
writeFileSync(
  "src/lib/trace/grid-data.ts",
  `// Generated by scripts/extract-grids.mjs from public/trace/*.svg. Do not edit by hand.\n// The real 35×21 grid of each decoded Trace character, one glyph per cell.\nexport const GRIDS: Record<number, string[]> = {\n${body}\n};\n`,
);
console.log(`wrote ${ids.length} grids`);
